name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'src/**.go'
      - 'src/go.mod'
      - .github/workflows/tests.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: src/go.mod
          cache-dependency-path: |
            src/go.sum
      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Go modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run quality checks and test code
        run: task ci
# Repo is not public yet so we cannot use this
#      - name: Upload Coverage
#        uses: codecov/codecov-action@v5
#        with:
#          files: ./src/coverage.txt
#          fail_ci_if_error: false
#          verbose: true
